[package]
name = "clipped-recorder"
description = "The Clipped recording process, which runs independently of the desktop application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "clipped-recorder"
path = "src/main.rs"

[dependencies]
clipped-session.workspace = true

[lints]
workspace = true
