//! The plugin as the host runs it: a process, a pipe, and a socket.
//!
//! Everything else in this crate tests a function. This installs the real
//! executable into a directory laid out like a plugin, runs its `install`
//! subcommand against a directory laid out like Counter-Strike 2, starts it the
//! way `clipped_plugins::PluginSupervisor` starts a plugin, POSTs the fixture
//! payloads to the port it opened, and reads the events it prints.
//!
//! It is the only test here that would notice the pieces not fitting: a token
//! written in one format and read in another, a manifest naming a binary that
//! is not built, an `attach` this plugin cannot parse, a socket bound before
//! `hello` is sent. Every one of those passes every unit test in the crate.
//!
//! No game is involved. What plays Counter-Strike's part is
//! `tests/payloads/competitive_match/`, posted by this test, and
//! `tests/payloads/README.md` is honest about where those came from.

use core::time::Duration;
use std::fs;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::mpsc::{self, Receiver, RecvTimeoutError};
use std::thread;

use clipped_events::EventKind;
use clipped_plugins::{HostCommand, ObservedProcess, PluginReport, SessionDetails, CONTRACT};

/// How long to wait for a line the plugin should already have written.
///
/// Generous: this is a process start on a machine that may be busy, and a test
/// that fails intermittently is worse than a slow one.
const PATIENCE: Duration = Duration::from_secs(20);

/// A plugin directory, a game directory, and the process between them.
struct Harness {
    root: PathBuf,
    executable: PathBuf,
    game: PathBuf,
    port: u16,
    token: String,
}

impl Harness {
    /// Lays out both directories and runs `install`, exactly as a user would.
    fn set_up(name: &str) -> Self {
        let root =
            std::env::temp_dir().join(format!("clipped-cs2-e2e-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let plugin = root.join("plugins").join("counter-strike-2");
        let game = root.join("Counter-Strike Global Offensive");
        fs::create_dir_all(&plugin).expect("a plugin directory");
        fs::create_dir_all(game.join("game").join("csgo").join("cfg")).expect("a game directory");

        // The plugin is the built binary, moved into a directory of its own,
        // because the plugin finds its own installation by looking beside
        // itself.
        let built = Path::new(env!("CARGO_BIN_EXE_clipped-cs2-plugin"));
        let executable = plugin.join(built.file_name().expect("the built binary has a name"));
        fs::copy(built, &executable).expect("the binary copies");
        fs::copy(
            Path::new(env!("CARGO_MANIFEST_DIR")).join("plugin.json"),
            plugin.join("plugin.json"),
        )
        .expect("the manifest copies");

        let port = free_port();
        let installed = Command::new(&executable)
            .arg("install")
            .arg(&game)
            .arg("--port")
            .arg(port.to_string())
            .output()
            .expect("install runs");
        assert!(
            installed.status.success(),
            "install failed: {}",
            String::from_utf8_lossy(&installed.stderr)
        );

        // The token is generated by `install` and read back out of the file the
        // game would read: nothing in this test knows it any other way, which
        // is the point.
        let configuration = game
            .join("game")
            .join("csgo")
            .join("cfg")
            .join("gamestate_integration_clipped.cfg");
        let text = fs::read_to_string(&configuration).expect("the configuration was written");
        let token = text
            .split_once("\"token\" \"")
            .and_then(|(_, rest)| rest.split_once('"'))
            .map(|(token, _)| token.to_owned())
            .unwrap_or_else(|| panic!("no token in:\n{text}"));
        assert!(
            text.contains(&format!("http://127.0.0.1:{port}/")),
            "the game was not told to post to the port that was asked for:\n{text}"
        );

        Self {
            root,
            executable,
            game,
            port,
            token,
        }
    }

    /// Starts the plugin the way the host does and hands over the `attach`.
    fn attach(&self) -> Running {
        let mut child = Command::new(&self.executable)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::inherit())
            .spawn()
            .expect("the plugin starts");

        // Printed so that a run which hangs can be matched against the machine's
        // process list afterwards. The suite runs four of these at once, each
        // holding a loopback port, and a log saying only "a plugin did not exit"
        // names none of them (issue #549).
        eprintln!(
            "clipped-cs2-plugin under test: process {} on port {}",
            child.id(),
            self.port
        );

        let attach = HostCommand::Attach {
            contract: CONTRACT,
            session: SessionDetails {
                session: "2026-08-12-cs2".to_owned(),
                process: ObservedProcess::new("cs2.exe", 4242),
            },
        };
        child
            .stdin
            .as_mut()
            .expect("stdin is piped")
            .write_all(attach.to_line().as_bytes())
            .expect("the attach goes");

        let stdout = child.stdout.take().expect("stdout is piped");
        let (sender, reports) = mpsc::channel();
        thread::spawn(move || {
            for line in BufReader::new(stdout).lines().map_while(Result::ok) {
                if sender.send(line).is_err() {
                    break;
                }
            }
        });

        Running { child, reports }
    }

    /// Posts one of the fixture payloads, with whichever token is given.
    fn post(&self, file: &str, token: &str) {
        let body = fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("tests")
                .join("payloads")
                .join(file),
        )
        .expect("the fixture reads")
        .replace("fixture-token-not-a-secret", token);

        let mut stream = connect(self.port);
        stream
            .write_all(
                format!(
                    "POST / HTTP/1.1\r\nHost: 127.0.0.1:{}\r\nContent-Type: application/json\r\n\
                     Content-Length: {}\r\n\r\n{body}",
                    self.port,
                    body.len()
                )
                .as_bytes(),
            )
            .expect("the payload goes");
        let mut answer = String::new();
        stream.read_to_string(&mut answer).expect("an answer comes");
        assert!(
            answer.starts_with("HTTP/1.1"),
            "the plugin answered with {answer}"
        );
    }
}

impl Drop for Harness {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

/// A plugin process and the lines it has written.
struct Running {
    child: Child,
    reports: Receiver<String>,
}

impl Running {
    /// The next report that is not a heartbeat.
    fn next_report(&self) -> PluginReport {
        loop {
            let line = match self.reports.recv_timeout(PATIENCE) {
                Ok(line) => line,
                Err(RecvTimeoutError::Timeout) => {
                    panic!("the plugin said nothing for {PATIENCE:?}")
                }
                Err(RecvTimeoutError::Disconnected) => panic!("the plugin stopped talking"),
            };
            let report = clipped_plugins::read_report(&line)
                .unwrap_or_else(|error| panic!("`{line}` is not a report: {error}"));
            if report != PluginReport::Alive {
                return report;
            }
        }
    }

    /// The next `n` events, in the order they were printed.
    fn next_events(&self, count: usize) -> Vec<clipped_plugins::ReportedEvent> {
        (0..count)
            .map(|_| match self.next_report() {
                PluginReport::Event(event) => event,
                other => panic!("expected an event, got {other:?}"),
            })
            .collect()
    }

    /// Asserts that no event at all is reported for `window`.
    ///
    /// An assertion about something *not* happening has to spend the time,
    /// which is why this is the only place in the file that waits. Heartbeats
    /// are expected and skipped; anything else is the failure.
    fn no_event_within(&self, window: Duration) {
        let deadline = std::time::Instant::now() + window;
        while let Some(remaining) = deadline.checked_duration_since(std::time::Instant::now()) {
            match self.reports.recv_timeout(remaining) {
                Ok(line) => {
                    let report = clipped_plugins::read_report(&line)
                        .unwrap_or_else(|error| panic!("`{line}` is not a report: {error}"));
                    assert_eq!(
                        report,
                        PluginReport::Alive,
                        "a payload that did not carry the token from the game's configuration \
                         file produced {report:?}"
                    );
                }
                Err(RecvTimeoutError::Timeout) => return,
                Err(RecvTimeoutError::Disconnected) => panic!("the plugin stopped talking"),
            }
        }
    }

    /// Sends `detach`, closes the pipe, and waits — for [`PATIENCE`], not for
    /// ever.
    ///
    /// # Panics
    ///
    /// If the plugin is still running [`PATIENCE`] after being detached. See
    /// [`wait_for_exit`] for why that bound is the whole point of this
    /// function.
    fn detach(mut self) -> std::process::ExitStatus {
        if let Some(stdin) = self.child.stdin.as_mut() {
            let _ = stdin.write_all(HostCommand::Detach.to_line().as_bytes());
        }
        drop(self.child.stdin.take());

        let pid = self.child.id();
        match wait_for_exit(&mut self.child, PATIENCE) {
            Ok(status) => status,
            Err(problem) => panic!(
                "{problem} after being detached (process {pid}). \
                 The last thing it said: {}",
                self.last_words()
            ),
        }
    }

    /// Everything the plugin wrote that no assertion consumed.
    ///
    /// The reader thread is still draining its standard output into the channel
    /// while [`detach`](Self::detach) waits, so a plugin that printed a
    /// `problem` on its way out has already said why — and until this existed
    /// that line was dropped on the floor, leaving a timeout whose message was
    /// only ever "it did not exit".
    ///
    /// Not an assertion, and deliberately not one: it is whatever is there, and
    /// on the run that produced [issue
    /// #549](https://github.com/wildware-uk/clipped/issues/549) there may be
    /// nothing at all. "nothing" is itself worth printing, because it rules the
    /// plugin's own error path out.
    fn last_words(&self) -> String {
        let mut lines = Vec::new();
        while let Ok(line) = self.reports.try_recv() {
            lines.push(line);
        }
        if lines.is_empty() {
            "nothing — it printed no report between the last assertion and the deadline".to_owned()
        } else {
            lines.join(" | ")
        }
    }
}

/// How often to ask whether a child has finished.
///
/// The same interval [`connect`] retries on. There is no way to wait on a
/// process handle *with a deadline* through [`std::process`], so this polls;
/// twenty-five milliseconds is far below the bound it is enforcing and far
/// above the cost of asking.
const POLL: Duration = Duration::from_millis(25);

/// Waits for `child` to exit of its own accord, for at most `patience`.
///
/// # Why this exists rather than [`Child::wait`]
///
/// [`Child::wait`] has no deadline, so a child that never exits is waited on
/// for ever. Every other wait in this file is bounded and fails with a sentence
/// naming what did not happen — [`PATIENCE`] in `next_report`, in `connect`, and
/// the window `no_event_within` spends — and `detach` was the one that was not.
///
/// It cost six hours. On [run
/// 31953786367](https://github.com/wildware-uk/clipped/actions/runs/31953786367)
/// the plugin did not exit after being detached, and the job was killed by
/// GitHub's six-hour limit with a log whose last line was "has been running for
/// over 60 seconds". Nothing said *what* had not happened, no other test in the
/// suite got to run, and the fault was intermittent — the same test passes in
/// six seconds ([issue
/// #549](https://github.com/wildware-uk/clipped/issues/549)).
///
/// This is the shape the product already uses:
/// `clipped_plugins::PluginProcess` asks a plugin to stop, gives it a grace
/// period it measures, and then kills it. A test harness that waits for ever on
/// the same cooperation was the outlier.
///
/// # What it does when the patience runs out
///
/// Kills the child and reports. Killing matters as much as the deadline: this
/// suite starts several plugin processes, each holding a loopback port, and
/// leaving one behind would make the *next* test fail for a reason that has
/// nothing to do with it.
///
/// # Errors
///
/// The sentence to fail with, naming what did not happen. The status is
/// returned as an [`Ok`] whatever it is — a plugin that exits with 101 is a
/// different fault from one that never exits, and it is the caller's to
/// assert.
fn wait_for_exit(
    child: &mut Child,
    patience: Duration,
) -> Result<std::process::ExitStatus, String> {
    let deadline = std::time::Instant::now() + patience;
    loop {
        match child
            .try_wait()
            .expect("a child this test spawned can be asked")
        {
            Some(status) => return Ok(status),
            None if std::time::Instant::now() >= deadline => {
                let _ = child.kill();
                // Reap it, so this does not leave a zombie behind the very
                // failure it is reporting. Bounded because the process is
                // already being terminated, which is the distinction this
                // whole function is about.
                let _ = child.wait();
                return Err(format!(
                    "the plugin was still running {patience:?} later, and was killed"
                ));
            }
            None => thread::sleep(POLL),
        }
    }
}

/// A loopback port nothing is using, as far as the operating system knows.
fn free_port() -> u16 {
    TcpListener::bind("127.0.0.1:0")
        .expect("an ephemeral port")
        .local_addr()
        .expect("its address")
        .port()
}

/// Connects, allowing for the plugin not having bound the socket yet.
fn connect(port: u16) -> TcpStream {
    let deadline = std::time::Instant::now() + PATIENCE;
    loop {
        match TcpStream::connect(("127.0.0.1", port)) {
            Ok(stream) => return stream,
            Err(error) if std::time::Instant::now() >= deadline => {
                panic!("the plugin never listened on {port}: {error}")
            }
            Err(_) => thread::sleep(Duration::from_millis(25)),
        }
    }
}

#[test]
fn the_plugin_installs_itself_listens_and_reports_what_the_game_posted() {
    let harness = Harness::set_up("happy-path");
    let running = harness.attach();

    assert_eq!(
        running.next_report(),
        PluginReport::Hello { contract: CONTRACT },
        "the first thing a plugin says is which contract it speaks"
    );

    // The baseline, which produces nothing, then the transitions that do.
    harness.post("competitive_match/00_menu.json", &harness.token);
    harness.post("competitive_match/01_warmup.json", &harness.token);
    let started = running.next_events(1);
    assert_eq!(started[0].kind, EventKind::MatchStarted);
    assert_eq!(started[0].data["map"], serde_json::json!("de_dust2"));

    harness.post("competitive_match/02_round_live.json", &harness.token);
    assert_eq!(running.next_events(1)[0].kind, EventKind::RoundStarted);

    harness.post("competitive_match/03_double_kill.json", &harness.token);
    let kills = running.next_events(2);
    assert!(kills.iter().all(|event| event.kind == EventKind::Kill));
    assert!(
        kills[0].ago_ns > 0,
        "a kill derived from a window has to be reported as having happened before now"
    );
    assert!(
        kills[0].precision_ns > 0,
        "a plugin that did not time an event exactly must not claim it did"
    );
    assert!(
        kills.iter().all(|event| event.confidence == 1.0),
        "Game State Integration is authoritative about what happened"
    );

    let status = running.detach();
    assert!(status.success(), "the plugin exited with {status}");
}

#[test]
fn a_payload_without_the_token_reaches_nothing() {
    // The requirement in `docs/privacy.md`: a loopback listener is reachable by
    // everything on the machine, so it must reject what it cannot authenticate
    // rather than trusting whatever arrives.
    //
    // Asserted as an absence, and it has to be: the payloads below would each
    // produce events if they were believed, so the only thing that distinguishes
    // a working token check from no token check at all is that nothing comes
    // out. That costs this test the wait below, and it is the difference between
    // proving the check works and proving the plugin can report an event.
    let harness = Harness::set_up("unauthenticated");
    let running = harness.attach();
    assert_eq!(
        running.next_report(),
        PluginReport::Hello { contract: CONTRACT }
    );

    harness.post("competitive_match/00_menu.json", &harness.token);
    harness.post("competitive_match/01_warmup.json", "not-the-token");
    harness.post("competitive_match/02_round_live.json", "not-the-token");
    harness.post("competitive_match/03_double_kill.json", "not-the-token");
    running.no_event_within(Duration::from_secs(3));

    // The same payload with the right token does produce one, so what the wait
    // above measured is the token check and not a plugin that reports nothing.
    harness.post("competitive_match/01_warmup.json", &harness.token);
    let report = running.next_report();
    assert!(
        matches!(&report, PluginReport::Event(event) if event.kind == EventKind::MatchStarted),
        "the first authentic transition should be reported, and was {report:?}"
    );

    running.detach();
}

#[test]
fn a_plugin_with_no_configuration_says_so_rather_than_installing_one() {
    // Writing into the user's game directory is not a side effect of a game
    // launching (`docs/privacy.md`). A plugin attached without one reports a
    // problem naming the command to run, and stops.
    let root = std::env::temp_dir().join(format!("clipped-cs2-e2e-bare-{}", std::process::id()));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).expect("a directory");
    let built = Path::new(env!("CARGO_BIN_EXE_clipped-cs2-plugin"));
    let executable = root.join(built.file_name().expect("a name"));
    fs::copy(built, &executable).expect("the binary copies");

    let mut child = Command::new(&executable)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("the plugin starts");
    let attach = HostCommand::Attach {
        contract: CONTRACT,
        session: SessionDetails {
            session: "bare".to_owned(),
            process: ObservedProcess::new("cs2.exe", 1),
        },
    };
    child
        .stdin
        .as_mut()
        .expect("stdin is piped")
        .write_all(attach.to_line().as_bytes())
        .expect("the attach goes");

    let mut lines = BufReader::new(child.stdout.take().expect("stdout is piped")).lines();
    let hello = lines.next().expect("a first line").expect("it reads");
    assert_eq!(
        clipped_plugins::read_report(&hello).expect("a report"),
        PluginReport::Hello { contract: CONTRACT },
        "a plugin that cannot start still introduces itself, so that the host reports what it \
         said rather than that it never spoke"
    );

    let problem = lines.next().expect("a second line").expect("it reads");
    let PluginReport::Problem { message } =
        clipped_plugins::read_report(&problem).expect("a report")
    else {
        panic!("expected a problem, got {problem}");
    };
    assert!(
        message.contains("install"),
        "the message has to leave the user an action: {message}"
    );

    let status = child.wait().expect("it exits");
    assert!(
        !status.success(),
        "a plugin that cannot do its job should not exit as though it did"
    );

    // And nothing was written anywhere: no configuration, no record.
    assert_eq!(
        fs::read_dir(&root).expect("the directory is there").count(),
        1,
        "a plugin that could not start wrote something"
    );
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn uninstall_takes_back_exactly_what_install_wrote() {
    let harness = Harness::set_up("uninstall");
    let configuration = harness
        .game
        .join("game")
        .join("csgo")
        .join("cfg")
        .join("gamestate_integration_clipped.cfg");
    assert!(configuration.exists());

    let status = Command::new(&harness.executable)
        .arg("status")
        .output()
        .expect("status runs");
    let said = String::from_utf8_lossy(&status.stdout).into_owned();
    assert!(
        said.contains("Installed") && said.contains(&harness.port.to_string()),
        "status should say where it is and what it listens on: {said}"
    );

    let removed = Command::new(&harness.executable)
        .arg("uninstall")
        .output()
        .expect("uninstall runs");
    assert!(
        removed.status.success(),
        "uninstall failed: {}",
        String::from_utf8_lossy(&removed.stderr)
    );
    assert!(
        !configuration.exists(),
        "the configuration file is still there"
    );
    assert!(
        harness.game.join("game").join("csgo").join("cfg").exists(),
        "uninstall removed more than the file it wrote"
    );

    let after = Command::new(&harness.executable)
        .arg("status")
        .output()
        .expect("status runs");
    assert!(String::from_utf8_lossy(&after.stdout).contains("Not installed"));
}

/// A child that will not exit on its own within any reasonable test's patience.
///
/// `ping -n 30 127.0.0.1` is thirty seconds of a program that is on every
/// Windows installation and ignores its standard input entirely, which is
/// exactly the shape being guarded against: a child that has been asked to stop
/// and has not.
fn a_child_that_will_not_stop() -> Child {
    Command::new("cmd")
        .args(["/c", "ping", "-n", "30", "127.0.0.1"])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("cmd.exe is on every Windows installation")
}

#[test]
fn a_plugin_that_will_not_exit_is_given_up_on_rather_than_waited_on() {
    // The bound that was missing, measured rather than read off the source.
    // Without it this call does not return for thirty seconds — and in the run
    // that produced issue #549, not for six hours.
    let mut child = a_child_that_will_not_stop();
    drop(child.stdin.take());

    let patience = Duration::from_millis(300);
    let started = std::time::Instant::now();
    let outcome = wait_for_exit(&mut child, patience);
    let waited = started.elapsed();

    let problem = outcome.expect_err("a child that ignores its input does not exit");
    assert!(
        problem.contains("still running") && problem.contains("killed"),
        "the failure has to say what did not happen and what was done about it: {problem}"
    );
    assert!(
        waited < patience * 10,
        "the wait is bounded by the patience it was given, and took {waited:?}"
    );
}

#[test]
fn a_child_that_will_not_stop_is_not_left_behind_when_it_is_given_up_on() {
    // The other half, and the reason the deadline alone is not enough: this
    // suite runs several plugin processes, each holding a loopback port. One
    // left running makes the *next* test fail for a reason of its own.
    let mut child = a_child_that_will_not_stop();
    drop(child.stdin.take());

    let _ = wait_for_exit(&mut child, Duration::from_millis(200));

    // Reaped: a second ask answers immediately with the status it was killed
    // with, rather than blocking on a process that is still running.
    let status = child
        .try_wait()
        .expect("a child this test spawned can be asked");
    assert!(
        status.is_some(),
        "the child was not killed and reaped, so it is still running"
    );
    assert!(
        !status.expect("just asserted").success(),
        "a killed process did not exit successfully"
    );
}

#[test]
fn a_child_that_does_stop_is_reported_rather_than_killed() {
    // The ordinary path, which the two tests above would still pass if this
    // function killed everything it was given.
    let mut child = Command::new("cmd")
        .args(["/c", "exit", "3"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("cmd.exe is on every Windows installation");

    let status = wait_for_exit(&mut child, PATIENCE).expect("it exits on its own");

    assert_eq!(
        status.code(),
        Some(3),
        "the status is the child's own, not one this function invented"
    );
}

/// A `Running` over a child that has already finished, with `lines` waiting to
/// be read.
///
/// The point is `last_words`, which needs a channel and a `Child` and nothing
/// else: the plugin it nominally describes never runs.
fn already_finished(lines: &[&str]) -> Running {
    let child = Command::new("cmd")
        .args(["/c", "exit", "0"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .expect("cmd.exe is on every Windows installation");

    let (sender, reports) = mpsc::channel();
    for line in lines {
        sender
            .send((*line).to_owned())
            .expect("the receiver is alive");
    }
    Running { child, reports }
}

#[test]
fn what_a_hung_plugin_last_said_reaches_the_failure_message() {
    // The whole value of the timeout is the sentence it fails with, and a
    // plugin that printed a `problem` on its way out has already said why. That
    // line used to be discarded.
    let running = already_finished(&[
        r#"{"report":"alive"}"#,
        r#"{"report":"problem","message":"the port was taken"}"#,
    ]);

    let said = running.last_words();

    assert!(said.contains("the port was taken"), "{said}");
    assert!(
        said.contains("alive"),
        "everything unread is reported, not only the last line: a heartbeat before the problem \
         is how long it kept going: {said}"
    );
}

#[test]
fn a_plugin_that_said_nothing_is_reported_as_having_said_nothing() {
    // Not an empty string. "It printed nothing" rules out the plugin's own
    // error path, which is a different fault from "it printed a problem", and a
    // message that trailed off after a colon would say neither.
    let said = already_finished(&[]).last_words();

    assert!(
        said.contains("nothing"),
        "an empty channel has to be reported in words: {said}"
    );
    assert!(!said.trim().is_empty());
}
