/**
 * The recorder control protocol in TypeScript: the messages, and the reading of
 * them.
 *
 * `docs/ipc.md` is the specification, `crates/ipc` the implementation, and
 * these files a mirror that a test holds against both on every run — see
 * `conformance.test.ts`. What is deliberately not here is the connection: the
 * pipe, the handshake sequence and the request-and-reply loop are issue #217.
 */

export type {
  ClientMessage,
  CommandName,
  ConnectionRole,
  ErrorCode,
  ErrorDetail,
  ErrorOutcome,
  EventMessage,
  EventStream,
  ExportProgress,
  ExportProgressEvent,
  ExportRecordingParams,
  ExportSummary,
  Extensible,
  Feature,
  ConflictingHotkey,
  Hello,
  HelloMessage,
  HotkeyBinding,
  HotkeysReply,
  HotkeyState,
  HotkeyStateName,
  IdleStatus,
  JsonObject,
  JsonValue,
  KnownCommandName,
  KnownConnectionRole,
  KnownEndReason,
  KnownErrorCode,
  KnownErrorDetailName,
  KnownEventName,
  KnownEventStream,
  KnownFeature,
  LibraryClip,
  LibraryEventLane,
  LibraryEventMark,
  LibraryEventsReply,
  LibraryTrashReply,
  FavouriteMark,
  FavouritedReply,
  LockMark,
  LockedReply,
  SetFavourite,
  SetLock,
  RestoredItem,
  RestoredReply,
  TrashEmptied,
  TrashEmptiedReply,
  TrashListing,
  TrashedItem,
  PluginDeclaration,
  PluginState,
  PluginsReply,
  RefusedPlugin,
  LibraryGame,
  LibraryGamesReply,
  LibraryRecording,
  LibrarySession,
  LibrarySessionPage,
  LibrarySessionsParams,
  LibrarySessionsReply,
  NotImplementedDetail,
  OkOutcome,
  OpenPlaybackParams,
  Outcome,
  PeerIdentity,
  PlaybackOpenedReply,
  PlaybackStream,
  PlaybackTrack,
  PongReply,
  ProtocolError,
  RecorderEvent,
  RecorderRequest,
  RecorderResponse,
  RecorderState,
  RecorderStatus,
  RecordingExportedReply,
  RecordingFailedEvent,
  RecordingStartedReply,
  RecordingStatus,
  RecordingStoppedReply,
  RecordingSummary,
  RefusedMessage,
  RegisteredHotkey,
  Reply,
  ReplyName,
  RequestMessage,
  ResponseMessage,
  ServerMessage,
  SessionEndedEvent,
  SessionRecording,
  SessionSummary,
  ApplySettingsParams,
  SettingEntry,
  SettingsReply,
  SettingsView,
  AudioDevice,
  AudioDevices,
  AudioDevicesReply,
  MicrophoneLevel,
  MicrophoneLevelParams,
  MicrophoneLevelReply,
  SetStartAtLoginParams,
  StartAtLogin,
  StartAtLoginReply,
  StartRecordingParams,
  StatusChangedEvent,
  StatusReply,
  StopRecordingParams,
  UnboundHotkey,
  UnrecognisedErrorDetail,
  UnrecognisedEvent,
  UnsupportedProtocolVersionDetail,
  WatchingStatus,
  WelcomeMessage,
  EndReason,
} from './protocol';

export {
  CLIENT_MESSAGE_TYPES,
  COMMANDS,
  CONNECTION_ROLES,
  DEFAULT_CONNECTION_ROLE,
  END_REASONS,
  ERROR_CODES,
  ERROR_DETAILS,
  EVENTS,
  EVENT_STREAMS,
  FEATURES,
  HOTKEY_STATES,
  MAX_CONCURRENT_CONNECTIONS,
  OUTCOMES,
  PROTOCOL_VERSION,
  RECORDER_STATES,
  REPLIES,
  SERVER_MESSAGE_TYPES,
  SUPPORTED_PROTOCOL_VERSIONS,
  exportFraction,
  hasFeature,
  isKnownErrorCode,
  isRecognisedErrorDetail,
  isRecognisedEvent,
} from './protocol';

export type { ParseResult } from './parse';
export { parseClientMessage, parseServerMessage } from './parse';

export type { FrameRead } from './frame';
export { LENGTH_PREFIX_BYTES, MAX_FRAME_BYTES, decodeFrame, encodeFrame } from './frame';
